package gui;

import gui.button.*;
import gui.panels.*;
import java.awt.Color;
import java.util.List;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import javax.swing.JFrame;
import javax.swing.SwingWorker;

public class MainMenu extends BaseMover {

    private LoadingPage loadingFrame;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        showLoadingFrame();

        new DataLoader().execute();
        
        // Expresion Lambda
        lblClose.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                cerrarApp();
            }
        });
    }

    private void showLoadingFrame() {
        loadingFrame = new LoadingPage();
        loadingFrame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        loadingFrame.toFront();
        loadingFrame.setVisible(true);
    }

    private void hideLoadingFrame() {
        loadingFrame.dispose();
        this.setVisible(true);
    }

    private class DataLoader extends SwingWorker<Void, Void> {
        @Override
        protected Void doInBackground() throws Exception {
            
            //Observador
            PanelManager panelManager = new PanelManager();

            //Lista de botones
            List<ButtonConfig> lista = new ArrayList<>();
            //Definimos nuestros botones:
            ButtonConfig home = new ButtonConfig("Home", FontIcon.of(FontAwesomeSolid.HOME, 22, Color.white), 0, 0, true, new HomePanel());
            ButtonConfig user = new ButtonConfig("Usuarios", FontIcon.of(FontAwesomeSolid.USERS, 22, Color.white), 0, 0, false, new UsuarioPanel());
            ButtonConfig prod = new ButtonConfig("Productos", FontIcon.of(FontAwesomeSolid.SHOPPING_BASKET, 22, Color.white), 0, 0, false, new ProductoPanel());
            ButtonConfig prov = new ButtonConfig("Proveedores", FontIcon.of(FontAwesomeSolid.CART_PLUS, 22, Color.white), 0, 0, false, new ProveedoresPanel());
            ButtonConfig inv = new ButtonConfig("Inventario", FontIcon.of(FontAwesomeSolid.WAREHOUSE, 20, Color.white), 0, 0, false, new InventarioPanel());
            ButtonConfig sum = new ButtonConfig("Suministros", FontIcon.of(FontAwesomeSolid.INBOX, 22, Color.white), 0, 0, false, new EntradaPanel());
            ButtonConfig coms = new ButtonConfig("Comsumos", FontIcon.of(FontAwesomeSolid.CART_ARROW_DOWN, 22, Color.white), 0, 0, false, new SalidaPanel());
            //Agregamos los botones a la lista
            lista.add(home);
            lista.add(user);
            lista.add(prod);
            lista.add(prov);
            lista.add(inv);
            lista.add(sum);
            lista.add(coms);
            
            int starY = 200;

            for (ButtonConfig bc : lista){
                bc.setYPoint(starY);
                panelButton comp = ButtonFactory.createButton(bc, panelManager, contentPanel);
                appBarPanel.add(comp, new AbsoluteConstraints(comp.getX(), comp.getY(), -1, -1));
                comp.setVisible(true);
                starY += 40;
            }
            
            //Icono de notificacion!
            lblNotificaciones.setIcon(FontIcon.of(FontAwesomeSolid.BELL, 16, Color.gray));
            return null;
        }

        @Override
        protected void done() {
            hideLoadingFrame();
        }
    }
    
    private void cerrarApp(){
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        appBarPanel = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblIconProgram = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JPanel();
        lblBienvenido = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblNotificaciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        appBarPanel.setBackground(new java.awt.Color(52, 58, 64));
        appBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/24x24/icons.png"))); // NOI18N
        appBarPanel.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, -1));

        lblIconProgram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/iso_170x58.png"))); // NOI18N
        lblIconProgram.setText("jLabel1");
        appBarPanel.add(lblIconProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 70, 170, 88));

        mainPanel.add(appBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 540));

        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenido.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        lblBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBienvenido.setText("Bienvenido EZER ISAI!");
        lblBienvenido.setToolTipText("");
        tituloPanel.add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 12, 290, -1));
        tituloPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 640, 10));

        lblNotificaciones.setToolTipText("");
        tituloPanel.add(lblNotificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 20, 20));

        contentPanel.add(tituloPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 640, 40));

        mainPanel.add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 720, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(false);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel appBarPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblIconProgram;
    private javax.swing.JLabel lblNotificaciones;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel tituloPanel;
    // End of variables declaration//GEN-END:variables
}