package gui.panels;

import appinventario.controllers.ProductoController;
import appinventario.models.Producto;
import appinventario.tablas.ProductoTableModel;
import java.util.List;

public class ProductoPanel extends ConfigPanel {

    private ProductoController controlador;
    
    public ProductoPanel() {
        initComponents();
        this.controlador = new ProductoController();
        llenarTabla();
    }

    private void llenarTabla(){
        List<Producto> usuarios = controlador.obtenerTodosProductos();
        ProductoTableModel modelo = new ProductoTableModel(usuarios);
        this.tablaProducto.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        pnlLista = new javax.swing.JPanel();
        jScrollJava = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        pnlBotones = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        bntEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        lblTitulo.setText("Productos");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, -1, -1));

        pnlLista.setLayout(new javax.swing.BoxLayout(pnlLista, javax.swing.BoxLayout.LINE_AXIS));

        jScrollJava.setOpaque(false);

        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProducto.setRowHeight(34);
        jScrollJava.setViewportView(tablaProducto);

        pnlLista.add(jScrollJava);

        add(pnlLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 640, 220));

        pnlBotones.setLayout(new java.awt.GridLayout(1, 0));

        btnAgregar.setBackground(new java.awt.Color(40, 167, 69));
        btnAgregar.setText("Agregar");
        pnlBotones.add(btnAgregar);

        btnModificar.setBackground(new java.awt.Color(255, 193, 7));
        btnModificar.setText("Modificar");
        btnModificar.setFocusPainted(false);
        pnlBotones.add(btnModificar);

        bntEliminar.setBackground(new java.awt.Color(220, 53, 69));
        bntEliminar.setText("Eliminar");
        bntEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bntEliminar.setFocusPainted(false);
        pnlBotones.add(bntEliminar);

        add(pnlBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 410, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Telefono");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, -1, -1));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, -1));

        jLabel3.setText("Apellido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 310, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 310, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 310, -1));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 200, -1));

        jLabel4.setText("Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 12, -1, -1));

        jLabel5.setText("Contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 42, -1, -1));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jTextField5.setText("123");
        jTextField5.setEnabled(false);
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 180, -1));

        jLabel6.setText("Cargo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 72, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Administrador" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 200, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 640, 100));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEliminar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollJava;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlLista;
    private javax.swing.JTable tablaProducto;
    // End of variables declaration//GEN-END:variables
}
